version: '3.1'

services:
  # camera1:
  #   image: camera-proxy
  #   container_name: camera1
  #   command: bash /app/streamKasa.sh 10.2.1.73 camera1 camera1
  #   restart: unless-stopped
  #   env_file:
  #     - cam.env
  #   volumes:
  #     - ./:/app
  camera2:
    image: camera-proxy
    container_name: camera2
    command: bash /app/streamKasa.sh 10.2.1.72 camera2 camera2
    restart: unless-stopped
    env_file:
      - cam.env
    volumes:
      - ./:/app
  camera3:
    image: camera-proxy
    container_name: camera3
    command: bash /app/streamKasa.sh 10.2.1.71 camera3 camera3
    restart: unless-stopped
    env_file:
      - cam.env
    volumes:
      - ./:/app
  camera4:
    image: camera-proxy
    container_name: camera4
    command: bash /app/streamKasa.sh 10.2.1.70 camera4 camera4
    restart: unless-stopped
    env_file:
      - cam.env
    volumes:
      - ./:/app
  listener:
    image: face-recognition
    container_name: listener
    command: python /app/listener.py
    restart: unless-stopped
    volumes:
      - ./:/app:rw